import { MaintenanceTask, CorridorSection, TrainMovement, ZonalRailway, DivisionalUnit } from './types';

// Authentic 18 Zonal Railways Data from Indian Railways Ministry Reports
export const ZONAL_RAILWAYS: ZonalRailway[] = [
  { code: 'NR', name: 'Northern Railway', hqCity: 'New Delhi', routeLengthKm: 7301, divisionsCount: 5, assetAvailabilityPercentage: 98.4, shadowEfficiencyPercentage: 54.2, activeDefectsCount: 1420 },
  { code: 'NCR', name: 'North Central Railway', hqCity: 'Prayagraj', routeLengthKm: 3151, divisionsCount: 3, assetAvailabilityPercentage: 98.8, shadowEfficiencyPercentage: 56.8, activeDefectsCount: 890 },
  { code: 'NER', name: 'North Eastern Railway', hqCity: 'Gorakhpur', routeLengthKm: 3864, divisionsCount: 3, assetAvailabilityPercentage: 97.5, shadowEfficiencyPercentage: 47.5, activeDefectsCount: 860 },
  { code: 'WR', name: 'Western Railway', hqCity: 'Mumbai (Churchgate)', routeLengthKm: 6182, divisionsCount: 6, assetAvailabilityPercentage: 98.1, shadowEfficiencyPercentage: 51.5, activeDefectsCount: 1210 },
  { code: 'CR', name: 'Central Railway', hqCity: 'Mumbai (CSMT)', routeLengthKm: 4151, divisionsCount: 5, assetAvailabilityPercentage: 97.9, shadowEfficiencyPercentage: 49.8, activeDefectsCount: 1350 },
  { code: 'ER', name: 'Eastern Railway', hqCity: 'Kolkata (Fairlie Place)', routeLengthKm: 2775, divisionsCount: 4, assetAvailabilityPercentage: 97.6, shadowEfficiencyPercentage: 48.2, activeDefectsCount: 980 },
  { code: 'SR', name: 'Southern Railway', hqCity: 'Chennai Central', routeLengthKm: 5079, divisionsCount: 6, assetAvailabilityPercentage: 98.2, shadowEfficiencyPercentage: 53.0, activeDefectsCount: 1100 },
  { code: 'SCR', name: 'South Central Railway', hqCity: 'Secunderabad', routeLengthKm: 6081, divisionsCount: 6, assetAvailabilityPercentage: 98.5, shadowEfficiencyPercentage: 55.1, activeDefectsCount: 1040 },
  { code: 'ECoR', name: 'East Coast Railway', hqCity: 'Bhubaneswar', routeLengthKm: 2727, divisionsCount: 3, assetAvailabilityPercentage: 97.4, shadowEfficiencyPercentage: 46.9, activeDefectsCount: 780 },
  { code: 'WCR', name: 'West Central Railway', hqCity: 'Jabalpur', routeLengthKm: 2997, divisionsCount: 3, assetAvailabilityPercentage: 98.6, shadowEfficiencyPercentage: 52.4, activeDefectsCount: 650 },
  { code: 'ECR', name: 'East Central Railway', hqCity: 'Hajipur', routeLengthKm: 4212, divisionsCount: 5, assetAvailabilityPercentage: 97.1, shadowEfficiencyPercentage: 45.3, activeDefectsCount: 1490 },
  { code: 'SECR', name: 'South East Central Railway', hqCity: 'Bilaspur', routeLengthKm: 2498, divisionsCount: 3, assetAvailabilityPercentage: 98.0, shadowEfficiencyPercentage: 50.1, activeDefectsCount: 590 },
  { code: 'SER', name: 'South Eastern Railway', hqCity: 'Kolkata (Garden Reach)', routeLengthKm: 2712, divisionsCount: 4, assetAvailabilityPercentage: 97.8, shadowEfficiencyPercentage: 49.0, activeDefectsCount: 820 },
  { code: 'SWR', name: 'South Western Railway', hqCity: 'Hubballi', routeLengthKm: 3566, divisionsCount: 3, assetAvailabilityPercentage: 98.3, shadowEfficiencyPercentage: 51.9, activeDefectsCount: 710 },
  { code: 'NWR', name: 'North Western Railway', hqCity: 'Jaipur', routeLengthKm: 5543, divisionsCount: 4, assetAvailabilityPercentage: 98.7, shadowEfficiencyPercentage: 53.6, activeDefectsCount: 920 },
  { code: 'NER_LKN', name: 'Lucknow Division (NER)', hqCity: 'Lucknow', routeLengthKm: 1240, divisionsCount: 1, assetAvailabilityPercentage: 97.8, shadowEfficiencyPercentage: 49.2, activeDefectsCount: 310 },
  { code: 'NFR', name: 'Northeast Frontier Railway', hqCity: 'Guwahati (Maligaon)', routeLengthKm: 4217, divisionsCount: 5, assetAvailabilityPercentage: 96.8, shadowEfficiencyPercentage: 42.1, activeDefectsCount: 1150 },
  { code: 'METRO', name: 'Kolkata Metro Railway', hqCity: 'Kolkata', routeLengthKm: 48, divisionsCount: 1, assetAvailabilityPercentage: 99.4, shadowEfficiencyPercentage: 62.0, activeDefectsCount: 45 },
];

// Authentic Divisional Units with Real Headquarter Locations
export const DIVISIONAL_UNITS: DivisionalUnit[] = [
  { code: 'PRYJ', name: 'Prayagraj Division', zoneCode: 'NCR', headquarters: 'Prayagraj', activeTasksCount: 340 },
  { code: 'AGC', name: 'Agra Division', zoneCode: 'NCR', headquarters: 'Agra Cantt', activeTasksCount: 220 },
  { code: 'JHS', name: 'Jhansi Division (VGLB)', zoneCode: 'NCR', headquarters: 'Virangana Lakshmibai Jhansi', activeTasksCount: 330 },
  { code: 'DLI', name: 'Delhi Division', zoneCode: 'NR', headquarters: 'New Delhi', activeTasksCount: 420 },
  { code: 'MB', name: 'Moradabad Division', zoneCode: 'NR', headquarters: 'Moradabad', activeTasksCount: 280 },
  { code: 'LJN', name: 'Lucknow Division (NER)', zoneCode: 'NER', headquarters: 'Lucknow Junction', activeTasksCount: 310 },
  { code: 'IZN', name: 'Izzatnagar Division (NER)', zoneCode: 'NER', headquarters: 'Bareilly (Izzatnagar)', activeTasksCount: 260 },
  { code: 'BSB', name: 'Varanasi Division (NER)', zoneCode: 'NER', headquarters: 'Varanasi', activeTasksCount: 290 },
  { code: 'MMCT', name: 'Mumbai Central Division', zoneCode: 'WR', headquarters: 'Mumbai', activeTasksCount: 380 },
  { code: 'BRC', name: 'Vadodara Division', zoneCode: 'WR', headquarters: 'Vadodara', activeTasksCount: 210 },
  { code: 'HWH', name: 'Howrah Division', zoneCode: 'ER', headquarters: 'Kolkata', activeTasksCount: 290 },
  { code: 'MAS', name: 'Chennai Division', zoneCode: 'SR', headquarters: 'Chennai', activeTasksCount: 310 },
  { code: 'NGP', name: 'Nagpur Division', zoneCode: 'CR', headquarters: 'Nagpur', activeTasksCount: 250 },
  { code: 'SC', name: 'Secunderabad Division', zoneCode: 'SCR', headquarters: 'Secunderabad', activeTasksCount: 320 },
  { code: 'JBP', name: 'Jabalpur Division', zoneCode: 'WCR', headquarters: 'Jabalpur', activeTasksCount: 240 },
];

// Real-World Railway Corridors & Actual Kilometer Markers
export const INITIAL_CORRIDOR_SECTIONS: CorridorSection[] = [
  // --- Delhi - Howrah Main Trunk Line (NR / NCR) ---
  {
    id: 'SEC-01',
    name: 'New Delhi - Faridabad Corridor',
    code: 'NDLS-FZB',
    zoneCode: 'NR',
    divisionCode: 'DLI',
    corridorName: 'Delhi - Howrah Main Trunk Route',
    startStation: 'NDLS (New Delhi)',
    endStation: 'FZB (Faridabad)',
    lengthKm: 30,
    startKm: 0,
    endKm: 30,
    tracks: 4,
    trafficDensity: 'VERY_HIGH',
    dailyTrainCount: 220,
  },
  {
    id: 'SEC-02',
    name: 'Faridabad - Mathura Junction',
    code: 'FZB-MTJ',
    zoneCode: 'NR',
    divisionCode: 'DLI',
    corridorName: 'Delhi - Howrah Main Trunk Route',
    startStation: 'FZB (Faridabad)',
    endStation: 'MTJ (Mathura Jn)',
    lengthKm: 110,
    startKm: 30,
    endKm: 140,
    tracks: 3,
    trafficDensity: 'VERY_HIGH',
    dailyTrainCount: 185,
  },
  {
    id: 'SEC-03',
    name: 'Mathura Jn - Agra Cantt',
    code: 'MTJ-AGC',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    corridorName: 'Delhi - Mumbai & Howrah Link',
    startStation: 'MTJ (Mathura Jn)',
    endStation: 'AGC (Agra Cantt)',
    lengthKm: 60,
    startKm: 140,
    endKm: 200,
    tracks: 2,
    trafficDensity: 'HIGH',
    dailyTrainCount: 160,
  },
  {
    id: 'SEC-04',
    name: 'Agra Cantt - Tundla Junction',
    code: 'AGC-TDL',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    corridorName: 'Delhi - Howrah Main Line',
    startStation: 'AGC (Agra Cantt)',
    endStation: 'TDL (Tundla Jn)',
    lengthKm: 50,
    startKm: 200,
    endKm: 250,
    tracks: 2,
    trafficDensity: 'HIGH',
    dailyTrainCount: 140,
  },
  {
    id: 'SEC-05',
    name: 'Tundla Junction - Kanpur Central',
    code: 'TDL-CNB',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    corridorName: 'Delhi - Howrah Main Line',
    startStation: 'TDL (Tundla Jn)',
    endStation: 'CNB (Kanpur Central)',
    lengthKm: 190,
    startKm: 250,
    endKm: 440,
    tracks: 2,
    trafficDensity: 'VERY_HIGH',
    dailyTrainCount: 210,
  },
  {
    id: 'SEC-06',
    name: 'Kanpur Central - Prayagraj Junction',
    code: 'CNB-PRYJ',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    corridorName: 'Delhi - Howrah Main Line',
    startStation: 'CNB (Kanpur Central)',
    endStation: 'PRYJ (Prayagraj Jn)',
    lengthKm: 194,
    startKm: 440,
    endKm: 634,
    tracks: 3,
    trafficDensity: 'VERY_HIGH',
    dailyTrainCount: 230,
  },
  {
    id: 'SEC-07',
    name: 'Prayagraj Jn - Pt. Deen Dayal Upadhyaya Jn',
    code: 'PRYJ-DDU',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    corridorName: 'Delhi - Howrah Main Line',
    startStation: 'PRYJ (Prayagraj Jn)',
    endStation: 'DDU (Pt. DD Upadhyaya)',
    lengthKm: 152,
    startKm: 634,
    endKm: 786,
    tracks: 2,
    trafficDensity: 'VERY_HIGH',
    dailyTrainCount: 190,
  },

  // --- North Eastern Railway (NER Gorakhpur - Lucknow Trunk) ---
  {
    id: 'SEC-08',
    name: 'Gorakhpur Jn - Basti Section',
    code: 'GKP-BST',
    zoneCode: 'NER',
    divisionCode: 'LJN',
    corridorName: 'Gorakhpur - Lucknow Main Line (NER)',
    startStation: 'GKP (Gorakhpur Jn)',
    endStation: 'BST (Basti)',
    lengthKm: 64,
    startKm: 0,
    endKm: 64,
    tracks: 2,
    trafficDensity: 'HIGH',
    dailyTrainCount: 110,
  },
  {
    id: 'SEC-09',
    name: 'Basti - Gonda Junction',
    code: 'BST-GD',
    zoneCode: 'NER',
    divisionCode: 'LJN',
    corridorName: 'Gorakhpur - Lucknow Main Line (NER)',
    startStation: 'BST (Basti)',
    endStation: 'GD (Gonda Jn)',
    lengthKm: 88,
    startKm: 64,
    endKm: 152,
    tracks: 2,
    trafficDensity: 'HIGH',
    dailyTrainCount: 125,
  },
  {
    id: 'SEC-10',
    name: 'Gonda Junction - Lucknow Junction',
    code: 'GD-LJN',
    zoneCode: 'NER',
    divisionCode: 'LJN',
    corridorName: 'Gorakhpur - Lucknow Main Line (NER)',
    startStation: 'GD (Gonda Jn)',
    endStation: 'LJN (Lucknow Jn)',
    lengthKm: 124,
    startKm: 152,
    endKm: 276,
    tracks: 2,
    trafficDensity: 'HIGH',
    dailyTrainCount: 140,
  },

  // --- Delhi - Mumbai Golden Corridor (WR) ---
  {
    id: 'SEC-11',
    name: 'Vadodara - Surat Corridor',
    code: 'BRC-ST',
    zoneCode: 'WR',
    divisionCode: 'BRC',
    corridorName: 'Delhi - Mumbai Golden Corridor',
    startStation: 'BRC (Vadodara Jn)',
    endStation: 'ST (Surat)',
    lengthKm: 130,
    startKm: 992,
    endKm: 1122,
    tracks: 2,
    trafficDensity: 'VERY_HIGH',
    dailyTrainCount: 195,
  },
  {
    id: 'SEC-12',
    name: 'Surat - Mumbai Central Section',
    code: 'ST-MMCT',
    zoneCode: 'WR',
    divisionCode: 'MMCT',
    corridorName: 'Delhi - Mumbai Golden Corridor',
    startStation: 'ST (Surat)',
    endStation: 'MMCT (Mumbai Central)',
    lengthKm: 264,
    startKm: 1122,
    endKm: 1386,
    tracks: 4,
    trafficDensity: 'VERY_HIGH',
    dailyTrainCount: 240,
  },
];

// Authentic Engineering Defect & Maintenance Tasks
export const INITIAL_MAINTENANCE_TASKS: MaintenanceTask[] = [
  // --- North Central Railway (NCR) Real Maintenance Tasks ---
  {
    id: 'TASK-ENG-101',
    sourceSystem: 'TMS',
    department: 'ENG',
    departmentName: 'Civil Engineering (Track)',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    title: 'IMR Rail Defect Replacement & Flash Butt Weld Grinding (KM 152.4)',
    sectionId: 'SEC-03',
    sectionName: 'MTJ-AGC',
    startKm: 152,
    endKm: 156,
    estimatedDurationHours: 2.5,
    severity: 'CRITICAL',
    overdueDays: 6,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 30,
    criticalityScore: 94,
    status: 'PENDING',
  },
  {
    id: 'TASK-TRD-301',
    sourceSystem: 'TDMS',
    department: 'TRD',
    departmentName: 'Traction Distribution (OHE)',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    title: '25kV OHE Cantilever Realignment & Contact Wire Height Tuning (KM 153.1)',
    sectionId: 'SEC-03',
    sectionName: 'MTJ-AGC',
    startKm: 153,
    endKm: 157,
    estimatedDurationHours: 2.0,
    severity: 'CRITICAL',
    overdueDays: 4,
    requiresPowerBlock: true,
    speedRestrictionImpactKmvh: 20,
    criticalityScore: 91,
    status: 'PENDING',
  },
  {
    id: 'TASK-SNT-201',
    sourceSystem: 'SMMS',
    department: 'SMMS',
    departmentName: 'Signal & Telecommunication',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    title: 'Point Machine 104-B Overhaul & High-Frequency Track Circuit Tuning',
    sectionId: 'SEC-03',
    sectionName: 'MTJ-AGC',
    startKm: 154,
    endKm: 155,
    estimatedDurationHours: 1.5,
    severity: 'HIGH',
    overdueDays: 2,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 15,
    criticalityScore: 82,
    status: 'PENDING',
  },

  // --- TDL-CNB & CNB-PRYJ Corridor Tasks ---
  {
    id: 'TASK-ENG-103',
    sourceSystem: 'TMS',
    department: 'ENG',
    departmentName: 'Civil Engineering (Track)',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    title: '1:12 Curved Switch Turnout Renewal (TTR) & Thermit Weld Replacement',
    sectionId: 'SEC-05',
    sectionName: 'TDL-CNB',
    startKm: 310,
    endKm: 314,
    estimatedDurationHours: 3.5,
    severity: 'CRITICAL',
    overdueDays: 12,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 50,
    criticalityScore: 97,
    status: 'PENDING',
  },
  {
    id: 'TASK-TRD-303',
    sourceSystem: 'TDMS',
    department: 'TRD',
    departmentName: 'Traction Distribution (OHE)',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    title: 'Neutral Section Phase Insulator Replacement & Tower Wagon Test',
    sectionId: 'SEC-05',
    sectionName: 'TDL-CNB',
    startKm: 311,
    endKm: 313,
    estimatedDurationHours: 2.5,
    severity: 'HIGH',
    overdueDays: 5,
    requiresPowerBlock: true,
    speedRestrictionImpactKmvh: 25,
    criticalityScore: 88,
    status: 'PENDING',
  },
  {
    id: 'TASK-SNT-203',
    sourceSystem: 'SMMS',
    department: 'SMMS',
    departmentName: 'Signal & Telecommunication',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    title: 'OFC Cable Splicing & Digital Axle Counter (DAC) Reset Tuning',
    sectionId: 'SEC-05',
    sectionName: 'TDL-CNB',
    startKm: 312,
    endKm: 314,
    estimatedDurationHours: 2.0,
    severity: 'HIGH',
    overdueDays: 5,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 20,
    criticalityScore: 84,
    status: 'PENDING',
  },
  {
    id: 'TASK-ENG-105',
    sourceSystem: 'TMS',
    department: 'ENG',
    departmentName: 'Civil Engineering (Track)',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    title: 'Continuous Track Tamping (CSM-12) & Ballast Regulating Machine Run',
    sectionId: 'SEC-06',
    sectionName: 'CNB-PRYJ',
    startKm: 510,
    endKm: 518,
    estimatedDurationHours: 3.0,
    severity: 'HIGH',
    overdueDays: 4,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 30,
    criticalityScore: 85,
    status: 'PENDING',
  },
  {
    id: 'TASK-TRD-305',
    sourceSystem: 'TDMS',
    department: 'TRD',
    departmentName: 'Traction Distribution (OHE)',
    zoneCode: 'NCR',
    divisionCode: 'PRYJ',
    title: '25kV AC Feeder Wire Re-tensioning & Mast Earthing Verification',
    sectionId: 'SEC-06',
    sectionName: 'CNB-PRYJ',
    startKm: 512,
    endKm: 516,
    estimatedDurationHours: 2.0,
    severity: 'MEDIUM',
    overdueDays: 2,
    requiresPowerBlock: true,
    speedRestrictionImpactKmvh: 10,
    criticalityScore: 71,
    status: 'PENDING',
  },

  // --- North Eastern Railway (NER) Real Maintenance Tasks ---
  {
    id: 'TASK-ENG-NER-101',
    sourceSystem: 'TMS',
    department: 'ENG',
    departmentName: 'Civil Engineering (Track)',
    zoneCode: 'NER',
    divisionCode: 'LJN',
    title: 'USFD Ultrasonic Flaw Detection & Rail End Fracture Clamp Repair',
    sectionId: 'SEC-08',
    sectionName: 'GKP-BST',
    startKm: 22,
    endKm: 26,
    estimatedDurationHours: 2.5,
    severity: 'CRITICAL',
    overdueDays: 5,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 30,
    criticalityScore: 93,
    status: 'PENDING',
  },
  {
    id: 'TASK-TRD-NER-301',
    sourceSystem: 'TDMS',
    department: 'TRD',
    departmentName: 'Traction Distribution (OHE)',
    zoneCode: 'NER',
    divisionCode: 'LJN',
    title: '25kV AC OHE Contact Wire Height & Stagger Laser Scan Alignment',
    sectionId: 'SEC-08',
    sectionName: 'GKP-BST',
    startKm: 23,
    endKm: 27,
    estimatedDurationHours: 2.0,
    severity: 'CRITICAL',
    overdueDays: 4,
    requiresPowerBlock: true,
    speedRestrictionImpactKmvh: 20,
    criticalityScore: 90,
    status: 'PENDING',
  },
  {
    id: 'TASK-SNT-NER-201',
    sourceSystem: 'SMMS',
    department: 'SMMS',
    departmentName: 'Signal & Telecommunication',
    zoneCode: 'NER',
    divisionCode: 'LJN',
    title: 'Electronic Interlocking (EI) & Kavach ATP RFID Tag Track Alignment',
    sectionId: 'SEC-08',
    sectionName: 'GKP-BST',
    startKm: 24,
    endKm: 25,
    estimatedDurationHours: 1.5,
    severity: 'HIGH',
    overdueDays: 2,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 15,
    criticalityScore: 83,
    status: 'PENDING',
  },

  // --- Western Railway (WR) Real Maintenance Tasks ---
  {
    id: 'TASK-ENG-104',
    sourceSystem: 'TMS',
    department: 'ENG',
    departmentName: 'Civil Engineering (Track)',
    zoneCode: 'WR',
    divisionCode: 'MMCT',
    title: 'Suburban Quadruple Track High-Speed Rail Grinding & Flange Profiling',
    sectionId: 'SEC-12',
    sectionName: 'ST-MMCT',
    startKm: 1310,
    endKm: 1315,
    estimatedDurationHours: 3.0,
    severity: 'CRITICAL',
    overdueDays: 8,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 40,
    criticalityScore: 95,
    status: 'PENDING',
  },
  {
    id: 'TASK-TRD-304',
    sourceSystem: 'TDMS',
    department: 'TRD',
    departmentName: 'Traction Distribution (OHE)',
    zoneCode: 'WR',
    divisionCode: 'MMCT',
    title: 'Suburban AC Traction Substation Isolator Maintenance & Thermal Scan',
    sectionId: 'SEC-12',
    sectionName: 'ST-MMCT',
    startKm: 1311,
    endKm: 1316,
    estimatedDurationHours: 2.5,
    severity: 'HIGH',
    overdueDays: 5,
    requiresPowerBlock: true,
    speedRestrictionImpactKmvh: 20,
    criticalityScore: 88,
    status: 'PENDING',
  },
  {
    id: 'TASK-SNT-304',
    sourceSystem: 'SMMS',
    department: 'SMMS',
    departmentName: 'Signal & Telecommunication',
    zoneCode: 'WR',
    divisionCode: 'MMCT',
    title: 'Automatic Block Signaling (ABS) Track Circuit Tuning & Relay Testing',
    sectionId: 'SEC-12',
    sectionName: 'ST-MMCT',
    startKm: 1312,
    endKm: 1314,
    estimatedDurationHours: 2.0,
    severity: 'HIGH',
    overdueDays: 3,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 25,
    criticalityScore: 85,
    status: 'PENDING',
  },

  // --- Northern Railway (NR) Delhi Division Tasks ---
  {
    id: 'TASK-ENG-102',
    sourceSystem: 'TMS',
    department: 'ENG',
    departmentName: 'Civil Engineering (Track)',
    zoneCode: 'NR',
    divisionCode: 'DLI',
    title: 'Ballast Cleaning Machine (BCM) Deep Screening & Shoulder Cleaning',
    sectionId: 'SEC-02',
    sectionName: 'FZB-MTJ',
    startKm: 75,
    endKm: 80,
    estimatedDurationHours: 3.0,
    severity: 'HIGH',
    overdueDays: 9,
    requiresPowerBlock: false,
    speedRestrictionImpactKmvh: 45,
    criticalityScore: 86,
    status: 'PENDING',
  },
  {
    id: 'TASK-TRD-302',
    sourceSystem: 'TDMS',
    department: 'TRD',
    departmentName: 'Traction Distribution (OHE)',
    zoneCode: 'NR',
    divisionCode: 'DLI',
    title: 'OHE Isolator Maintenance & Dropper Wire Replacement (Tower Wagon)',
    sectionId: 'SEC-02',
    sectionName: 'FZB-MTJ',
    startKm: 76,
    endKm: 79,
    estimatedDurationHours: 2.5,
    severity: 'MEDIUM',
    overdueDays: 3,
    requiresPowerBlock: true,
    speedRestrictionImpactKmvh: 10,
    criticalityScore: 68,
    status: 'PENDING',
  },
];

// Authentic Passenger & Freight Train Schedules
export const INITIAL_TRAIN_MOVEMENTS: TrainMovement[] = [
  // --- High-Speed Premium Passenger Trains (Hard Constraints) ---
  {
    id: 'TRN-22436',
    trainNumber: '22436',
    trainName: 'Vande Bharat Express (NDLS - BSB)',
    type: 'PASSENGER_EXPRESS',
    sectionId: 'SEC-03',
    originZone: 'NR',
    destinationZone: 'NCR',
    entryTime: '06:15',
    exitTime: '06:55',
    priority: 1,
  },
  {
    id: 'TRN-20172',
    trainNumber: '20172',
    trainName: 'Vande Bharat Express (NDLS - AYC)',
    type: 'PASSENGER_EXPRESS',
    sectionId: 'SEC-01',
    originZone: 'NR',
    destinationZone: 'NR',
    entryTime: '07:00',
    exitTime: '07:35',
    priority: 1,
  },
  {
    id: 'TRN-12002',
    trainNumber: '12002',
    trainName: 'Bhopal Shatabdi Express (NDLS - RKMP)',
    type: 'PASSENGER_EXPRESS',
    sectionId: 'SEC-03',
    originZone: 'NR',
    destinationZone: 'WCR',
    entryTime: '07:45',
    exitTime: '08:20',
    priority: 1,
  },
  {
    id: 'TRN-12302',
    trainNumber: '12302',
    trainName: 'Howrah Rajdhani Express (NDLS - HWH)',
    type: 'PASSENGER_EXPRESS',
    sectionId: 'SEC-03',
    originZone: 'NR',
    destinationZone: 'ER',
    entryTime: '08:30',
    exitTime: '09:10',
    priority: 1,
  },
  {
    id: 'TRN-12556',
    trainNumber: '12556',
    trainName: 'Gorakhdham Express (GKP - HISAR)',
    type: 'PASSENGER_EXPRESS',
    sectionId: 'SEC-08',
    originZone: 'NER',
    destinationZone: 'NR',
    entryTime: '09:30',
    exitTime: '10:20',
    priority: 1,
  },
  {
    id: 'TRN-12952',
    trainNumber: '12952',
    trainName: 'Mumbai Rajdhani Express (NDLS - MMCT)',
    type: 'PASSENGER_EXPRESS',
    sectionId: 'SEC-12',
    originZone: 'NR',
    destinationZone: 'WR',
    entryTime: '16:00',
    exitTime: '18:30',
    priority: 1,
  },
  {
    id: 'TRN-12418',
    trainNumber: '12418',
    trainName: 'Prayagraj Express (NDLS - PRYJ)',
    type: 'PASSENGER_EXPRESS',
    sectionId: 'SEC-06',
    originZone: 'NR',
    destinationZone: 'NCR',
    entryTime: '22:15',
    exitTime: '23:45',
    priority: 1,
  },

  // --- Freight Goods Rakes & Parcel Specials (Regulatable Soft Constraints) ---
  {
    id: 'TRN-G8891',
    trainNumber: 'G-8891',
    trainName: 'CONCOR High-Cube Container Express Rake',
    type: 'FREIGHT_GOODS',
    sectionId: 'SEC-03',
    originZone: 'WR',
    destinationZone: 'NCR',
    entryTime: '11:00',
    exitTime: '12:15',
    priority: 3,
  },
  {
    id: 'TRN-C4412',
    trainNumber: 'C-4412',
    trainName: 'NTPC Thermal Coal Heavy Haul Rake',
    type: 'FREIGHT_GOODS',
    sectionId: 'SEC-05',
    originZone: 'SECR',
    destinationZone: 'NCR',
    entryTime: '18:45',
    exitTime: '20:00',
    priority: 3,
  },
  {
    id: 'TRN-P9921',
    trainNumber: 'P-9921',
    trainName: 'IOCL BTPN Petroleum Tanker Express',
    type: 'FREIGHT_GOODS',
    sectionId: 'SEC-11',
    originZone: 'WR',
    destinationZone: 'NCR',
    entryTime: '14:30',
    exitTime: '16:00',
    priority: 3,
  },
  {
    id: 'TRN-S7714',
    trainNumber: 'S-7714',
    trainName: 'SAIL BOST Steel Coil Special Freight',
    type: 'FREIGHT_GOODS',
    sectionId: 'SEC-07',
    originZone: 'SER',
    destinationZone: 'NR',
    entryTime: '01:30',
    exitTime: '03:15',
    priority: 3,
  },
];
